import AdmZip from "adm-zip";
import { parse } from "csv-parse";
import {
  and,
  asc,
  count,
  desc,
  eq,
  getTableColumns,
  gte,
  inArray,
  isNotNull,
  isNull,
  like,
  lte,
  ne,
  notInArray,
  notLike,
  or,
  sql,
  SQL,
} from "drizzle-orm";
import type { MySqlColumn } from "drizzle-orm/mysql-core";
import { db } from "../../config/db.js";
import { getConfig } from "../../config/config.js";
import { AppError } from "../../utils/AppError.js";
import { anuraRequest } from "./anura.client.js";
import { DIRECT_RAW_COLUMNS, LIMITS, RAW_FACET_COLUMNS } from "./anura.constants.js";
import { addDays, assertRange, toAnuraDate, todayUtc } from "./anura.services.js";
import { rawImports, RawImportRow, RawRowColumn, rawRows } from "./rawData.model.js";

/* ----------------------------------------------------------------------------------------------
 * Raw data reports: row level data that Anura generates asynchronously. A report is requested,
 * polled until "Ready", then downloaded and imported into MySQL for server side filtering.
 * -------------------------------------------------------------------------------------------- */

const { id: _id, reportId: _reportId, ...dataColumns } = getTableColumns(rawRows);
const COLUMNS = dataColumns as Record<RawRowColumn, MySqlColumn>;
const isKnownColumn = (key: string): key is RawRowColumn => key in COLUMNS;

// A stuck import (e.g. the server restarted mid import) may be retried after this long.
const STALE_IMPORT_MS = 30 * 60_000;

// Reports requested with autoImport that are still being generated by Anura.
const pendingAutoImports = new Set<string>();

const formatImport = (i: RawImportRow | undefined | null) =>
  i
    ? {
        status: i.status,
        rows: i.rows,
        columns: i.columns ?? [],
        error: i.error ?? null,
        importedAt: i.importedAt ?? null,
      }
    : null;

const getImport = async (reportId: string) => {
  const [imp] = await db.select().from(rawImports).where(eq(rawImports.reportId, reportId)).limit(1);
  return imp ?? null;
};

export const listRawReports = async (o: { page?: number; limit?: number; search?: string }) => {
  const res = await anuraRequest(
    "/raw/table",
    { page: o.page, limit: o.limit ?? 50, search: o.search, sort: "3:desc" },
    { ttlMs: 3_000 },
  );
  const rows = (res.table?.rows ?? []) as any[];
  const ids = rows.map((r) => String(r.id));
  const imports = ids.length ? await db.select().from(rawImports).where(inArray(rawImports.reportId, ids)) : [];
  const importById = new Map(imports.map((i) => [i.reportId, i]));

  return {
    limits: res.processing?.limits ?? null,
    reports: rows.map((r) => ({
      ...r,
      autoImport: pendingAutoImports.has(String(r.id)),
      import: formatImport(importById.get(String(r.id))),
    })),
    pagination: {
      page: Number(res.query?.page ?? 1),
      pages: Number(res.query?.pages ?? 1),
      results: Number(res.query?.results ?? rows.length),
    },
  };
};

export const getRawReport = async (id: string) => {
  const report = await anuraRequest("/raw/report", { raw: id }, { ttlMs: 0 });
  return { ...report, autoImport: pendingAutoImports.has(id), import: formatImport(await getImport(id)) };
};

export type RawFilter = { column: string; operator: string; value?: string };

export const requestRawReport = async (input: {
  start: string;
  end: string;
  instance?: string;
  name?: string;
  standard?: string[];
  additional?: number[];
  filters?: RawFilter[];
}) => {
  const oldest = addDays(todayUtc(), -LIMITS.rawMaxAgeDays);
  if (input.start < oldest) {
    throw new AppError(`Raw data is only available for the last ${LIMITS.rawMaxAgeDays} days`, 400);
  }
  assertRange(input.start, input.end, LIMITS.rawMaxAgeDays + 1);

  const instance = input.instance || getConfig().ANURA_INSTANCE_ID;
  if (!instance) throw new AppError("Choose an instance (or set ANURA_INSTANCE_ID)", 400);

  const res = await anuraRequest(
    "/raw/request",
    {
      type: "direct",
      instance,
      start: toAnuraDate(input.start),
      end: toAnuraDate(input.end),
      standard: input.standard?.length ? input.standard : [...DIRECT_RAW_COLUMNS],
      additional: input.additional?.length ? input.additional : undefined,
      filters: input.filters?.length
        ? input.filters.map((f) =>
            f.operator === "empty" || f.operator === "not_empty" ? { column: f.column, operator: f.operator } : f,
          )
        : undefined,
      name: input.name,
      send_email: false,
    },
    { ttlMs: 0 },
  );
  if (res.success === false) throw new AppError(res.message ?? "Anura rejected the report request", 400);
  return res as { success: boolean; message: string; id: string };
};

/**
 * Polls Anura until a freshly requested report is ready, then imports it. Runs server side so
 * the import completes even if nobody keeps the dashboard open.
 */
export const watchAndImport = (reportId: string, userId: number) => {
  pendingAutoImports.add(reportId);
  const deadline = Date.now() + 30 * 60_000;

  const tick = async () => {
    try {
      const report = await anuraRequest("/raw/report", { raw: reportId }, { ttlMs: 0 });
      if (report.status === "Ready") {
        pendingAutoImports.delete(reportId);
        await startRawImport(reportId, userId);
        return;
      }
      if (["Failed", "Timed Out", "Cancelled"].includes(report.status) || Date.now() > deadline) {
        pendingAutoImports.delete(reportId);
        return;
      }
    } catch (err) {
      if (Date.now() > deadline) {
        pendingAutoImports.delete(reportId);
        console.error(`Auto import of ${reportId} gave up:`, err);
        return;
      }
    }
    setTimeout(tick, 4_000);
  };
  setTimeout(tick, 3_000);
};

export const cancelRawReport = (id: string) => {
  pendingAutoImports.delete(id);
  return anuraRequest("/raw/cancel", { raw: id }, { ttlMs: 0 });
};

export const removeRawReport = async (id: string) => {
  const res = await anuraRequest("/raw/remove", { raw: id }, { ttlMs: 0 });
  await deleteRawImport(id);
  return res;
};

export const deleteRawImport = async (id: string) => {
  await db.delete(rawRows).where(eq(rawRows.reportId, id));
  await db.delete(rawImports).where(eq(rawImports.reportId, id));
};

/* ---- Import: download the finished report from Anura and load it into MySQL ---- */

const headerToKey = (header: string) =>
  header
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");

/** Anura reports in UTC, so timestamps without an explicit zone are read as UTC. */
const parseTimestamp = (value: string): Date | null => {
  // M/D/YYYY H:mm[:ss] (as rendered by spreadsheet apps)
  const m = value.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})(?:[ T](\d{1,2}):(\d{2})(?::(\d{2}))?)?$/);
  if (m) {
    const [, mo, d, y, h = "0", mi = "0", s = "0"] = m;
    return new Date(Date.UTC(+y, +mo - 1, +d, +h, +mi, +s));
  }
  const zoneless = /^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}(:\d{2}(\.\d+)?)?$/.test(value);
  const time = Date.parse(zoneless ? `${value.replace(" ", "T")}Z` : value);
  return Number.isNaN(time) ? null : new Date(time);
};

const convertValue = (key: RawRowColumn, value: string | undefined): unknown => {
  if (value === undefined || value === "") return null;
  if (key === "timestamp") return parseTimestamp(value);
  if (key === "mobile") {
    const v = value.toLowerCase();
    return v === "true" || v === "1" ? true : v === "false" || v === "0" ? false : null;
  }
  const max = (COLUMNS[key] as { length?: number }).length;
  return max && value.length > max ? value.slice(0, max) : value;
};

const extractCsv = (buffer: Buffer): Buffer => {
  // ZIP files start with "PK"
  if (buffer[0] === 0x50 && buffer[1] === 0x4b) {
    const entry = new AdmZip(buffer)
      .getEntries()
      .find((e) => !e.isDirectory && e.entryName.toLowerCase().endsWith(".csv"));
    if (!entry) throw new Error("The report archive does not contain a CSV file");
    return entry.getData();
  }
  return buffer;
};

const runImport = async (reportId: string) => {
  const { url } = await anuraRequest("/raw/download", { raw: reportId }, { ttlMs: 0 });
  const allowHttp = !getConfig().isProduction;
  if (typeof url !== "string" || !(url.startsWith("https://") || (allowHttp && url.startsWith("http://")))) {
    throw new Error("Anura did not return a valid download URL");
  }

  const res = await fetch(url, { signal: AbortSignal.timeout(10 * 60_000) });
  if (!res.ok) throw new Error(`Download failed with HTTP ${res.status}`);
  const csv = extractCsv(Buffer.from(await res.arrayBuffer()));

  await db.delete(rawRows).where(eq(rawRows.reportId, reportId));

  const parser = parse(csv, { bom: true, relax_column_count: true, skip_empty_lines: true });
  let columns: (RawRowColumn | null)[] | null = null;
  let batch: (typeof rawRows.$inferInsert)[] = [];
  let total = 0;

  const flush = async () => {
    if (!batch.length) return;
    await db.insert(rawRows).values(batch);
    total += batch.length;
    batch = [];
  };

  for await (const record of parser as AsyncIterable<string[]>) {
    if (!columns) {
      // Unknown headers are skipped rather than failing the import.
      columns = record.map((h) => {
        const key = headerToKey(h);
        return isKnownColumn(key) ? key : null;
      });
      continue;
    }
    const row: Record<string, unknown> = { reportId };
    columns.forEach((key, i) => {
      if (key) row[key] = convertValue(key, record[i]);
    });
    batch.push(row as typeof rawRows.$inferInsert);
    if (batch.length >= 1000) await flush();
  }
  await flush();

  await db
    .update(rawImports)
    .set({
      status: "ready",
      rows: total,
      columns: (columns ?? []).filter((c): c is RawRowColumn => c !== null),
      importedAt: new Date(),
      error: null,
    })
    .where(eq(rawImports.reportId, reportId));
};

export const startRawImport = async (reportId: string, userId: number) => {
  const report = await anuraRequest("/raw/report", { raw: reportId }, { ttlMs: 0 });
  if (report.status !== "Ready") {
    throw new AppError(`Report is not ready yet (status: ${report.status ?? "unknown"})`, 409);
  }

  const existing = await getImport(reportId);
  if (existing?.status === "importing" && Date.now() - existing.startedAt.getTime() < STALE_IMPORT_MS) {
    return formatImport(existing);
  }

  const values = {
    name: report.name ?? null,
    type: report.type ?? null,
    instanceName: report.instance_name ?? null,
    start: report.start ? Number(report.start) : null,
    end: report.end ? Number(report.end) : null,
    status: "importing" as const,
    rows: 0,
    error: null,
    importedBy: userId,
    startedAt: new Date(),
  };
  await db
    .insert(rawImports)
    .values({ reportId, ...values })
    .onDuplicateKeyUpdate({ set: values });

  // Runs in the background; the client polls the report for import status.
  runImport(reportId).catch(async (err) => {
    console.error(`Raw import ${reportId} failed:`, err);
    await db
      .update(rawImports)
      .set({ status: "failed", error: String(err?.message ?? err).slice(0, 2000) })
      .where(eq(rawImports.reportId, reportId));
  });

  return { status: "importing", rows: 0, columns: [], error: null, importedAt: null };
};

/* ---- Query imported rows ---- */

export type RowFilter = { column: string; operator: string; value?: string | string[] };

export type RowQuery = {
  page: number;
  limit: number;
  sort?: string;
  dir?: "asc" | "desc";
  q?: string;
  filters?: RowFilter[];
};

const escapeLike = (s: string) => s.replace(/[\\%_]/g, (c) => `\\${c}`);

const coerce = (column: RawRowColumn, value: string): any => {
  if (column === "mobile") return value === "true";
  if (column === "timestamp") {
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) throw new AppError(`Invalid date: ${value}`, 400);
    return d;
  }
  return value;
};

const buildRowWhere = (reportId: string, columns: string[], query: Pick<RowQuery, "q" | "filters">) => {
  const allowed = new Set(columns);
  const conditions: (SQL | undefined)[] = [eq(rawRows.reportId, reportId)];

  for (const f of query.filters ?? []) {
    if (!allowed.has(f.column) || !isKnownColumn(f.column)) throw new AppError(`Unknown column: ${f.column}`, 400);
    const key = f.column;
    const col = COLUMNS[key];
    const values = (Array.isArray(f.value) ? f.value : [f.value ?? ""]).map(String);
    const v = values[0];
    const textual = key !== "mobile" && key !== "timestamp";

    switch (f.operator) {
      case "in":
        if (values.length) conditions.push(inArray(col, values.map((x) => coerce(key, x))));
        break;
      case "not_in":
        if (values.length) conditions.push(or(notInArray(col, values.map((x) => coerce(key, x))), isNull(col)));
        break;
      case "equals":
        conditions.push(eq(col, coerce(key, v)));
        break;
      case "not_equals":
        conditions.push(or(ne(col, coerce(key, v)), isNull(col)));
        break;
      case "contains":
        conditions.push(like(col, `%${escapeLike(v)}%`));
        break;
      case "not_contains":
        conditions.push(or(notLike(col, `%${escapeLike(v)}%`), isNull(col)));
        break;
      case "starts_with":
        conditions.push(like(col, `${escapeLike(v)}%`));
        break;
      case "ends_with":
        conditions.push(like(col, `%${escapeLike(v)}`));
        break;
      case "empty":
        conditions.push(textual ? or(isNull(col), eq(col, "")) : isNull(col));
        break;
      case "not_empty":
        conditions.push(textual ? and(isNotNull(col), ne(col, "")) : isNotNull(col));
        break;
      case "gte":
        conditions.push(gte(col, coerce(key, v)));
        break;
      case "lte":
        conditions.push(lte(col, coerce(key, v)));
        break;
      default:
        throw new AppError(`Unknown operator: ${f.operator}`, 400);
    }
  }

  const q = query.q?.trim();
  if (q) {
    const pattern = `%${escapeLike(q)}%`;
    const searchable = columns.filter((c): c is RawRowColumn => isKnownColumn(c) && c !== "timestamp" && c !== "mobile");
    conditions.push(or(...searchable.map((c) => like(COLUMNS[c], pattern))));
  }

  return and(...conditions);
};

const getReadyImport = async (reportId: string) => {
  const imp = await getImport(reportId);
  if (!imp) throw new AppError("This report has not been imported yet", 404);
  if (imp.status !== "ready") throw new AppError(`Import is ${imp.status}`, 409);
  return { ...imp, columns: imp.columns ?? [] };
};

export const queryRawRows = async (reportId: string, query: RowQuery) => {
  const imp = await getReadyImport(reportId);
  const where = buildRowWhere(reportId, imp.columns, query);

  const sortKey = query.sort && imp.columns.includes(query.sort) && isKnownColumn(query.sort) ? query.sort : "timestamp";
  const direction = query.dir === "asc" ? asc : desc;

  const [rows, [{ n }]] = await Promise.all([
    db
      .select({ id: rawRows.id, ...dataColumns })
      .from(rawRows)
      .where(where)
      .orderBy(direction(COLUMNS[sortKey]), asc(rawRows.id))
      .limit(query.limit)
      .offset((query.page - 1) * query.limit),
    db.select({ n: count() }).from(rawRows).where(where),
  ]);

  // Only return the columns this report actually has.
  const keep = new Set(["id", ...imp.columns]);
  return {
    columns: imp.columns,
    rows: rows.map((r) => Object.fromEntries(Object.entries(r).filter(([k]) => keep.has(k)))),
    pagination: {
      page: query.page,
      limit: query.limit,
      results: n,
      pages: Math.max(1, Math.ceil(n / query.limit)),
      total: imp.rows,
    },
    sort: { column: sortKey, dir: query.dir === "asc" ? "asc" : "desc" },
  };
};

/** Distinct values of one column (with row counts) for pickers, optionally narrowed by a search. */
export const getRawValues = async (
  reportId: string,
  query: { column: string; q?: string; filters?: RowFilter[] },
) => {
  const imp = await getReadyImport(reportId);
  const key = query.column;
  if (!imp.columns.includes(key) || !isKnownColumn(key)) throw new AppError(`Unknown column: ${key}`, 400);
  const col = COLUMNS[key];
  const search = query.q?.trim();

  const rows = await db
    .select({ value: col, count: count() })
    .from(rawRows)
    .where(
      and(
        buildRowWhere(reportId, imp.columns, { filters: query.filters }),
        isNotNull(col),
        search ? like(col, `%${escapeLike(search)}%`) : undefined,
      ),
    )
    .groupBy(col)
    .orderBy(desc(count()))
    .limit(500);

  return rows.map((r) => ({ value: String(r.value), count: r.count }));
};

/** Value counts per column plus an hourly timeline, respecting the current filters. */
export const getRawFacets = async (reportId: string, query: Pick<RowQuery, "q" | "filters">) => {
  const imp = await getReadyImport(reportId);
  const where = buildRowWhere(reportId, imp.columns, query);
  const facetColumns = RAW_FACET_COLUMNS.filter((c): c is RawRowColumn => imp.columns.includes(c) && isKnownColumn(c));

  const facetQuery = (key: RawRowColumn, limit: number) =>
    db
      .select({ value: COLUMNS[key], count: count() })
      .from(rawRows)
      .where(where)
      .groupBy(COLUMNS[key])
      .orderBy(desc(count()))
      .limit(limit);

  const [[{ n }], timeline, ...facetResults] = await Promise.all([
    db.select({ n: count() }).from(rawRows).where(where),
    imp.columns.includes("timestamp")
      ? db
          .select({
            hour: sql<string>`DATE_FORMAT(${rawRows.timestamp}, '%Y-%m-%dT%H:00:00Z')`.as("hour"),
            total: count(),
            suspect: sql<string>`SUM(${rawRows.result} = 'suspect')`,
          })
          .from(rawRows)
          .where(and(where, isNotNull(rawRows.timestamp)))
          .groupBy(sql`hour`)
          .orderBy(sql`hour`)
          .limit(24 * 92)
      : Promise.resolve([]),
    // rule_sets holds comma separated lists ("DC, WC"), so fetch combinations and split below.
    ...facetColumns.map((key) => facetQuery(key, key === "rule_sets" ? 1000 : 30)),
  ]);

  const facets: Record<string, { value: string | boolean | null; count: number }[]> = {};
  facetColumns.forEach((key, i) => {
    const buckets = facetResults[i] as { value: unknown; count: number }[];
    if (key === "rule_sets") {
      const totals = new Map<string, number>();
      for (const b of buckets) {
        for (const part of String(b.value ?? "").split(",")) {
          const rule = part.trim();
          if (rule) totals.set(rule, (totals.get(rule) ?? 0) + b.count);
        }
      }
      facets[key] = [...totals]
        .map(([value, c]) => ({ value, count: c }))
        .sort((a, b) => b.count - a.count)
        .slice(0, 30);
    } else {
      facets[key] = buckets.map((b) => ({ value: (b.value as string | boolean | null) ?? null, count: b.count }));
    }
  });

  return {
    total: n,
    facets,
    timeline: timeline.map((b) => {
      const suspect = Number(b.suspect ?? 0);
      return { hour: b.hour, total: b.total, suspect, nonsuspect: b.total - suspect };
    }),
  };
};
